# Generated by Django 4.0.1 on 2022-01-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('list', 'Список'), ('block', 'Блоки')], default='list', max_length=20, verbose_name='Тип блоков'),
        ),
    ]
